apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-backend
  namespace: hr-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-backend
  template:
    metadata:
      labels:
        app: hr-backend
    spec:
      containers:
        - name: hr-backend
          image: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/hr-backend:latest # Placeholder
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: hr-common-config
            - secretRef:
                name: hr-secrets
#          livenessProbe:
#            httpGet:
#              path: /api/v1/health
#              port: 8082
#            initialDelaySeconds: 60
#            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hr-backend
  namespace: hr-system
spec:
  selector:
    app: hr-backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
