apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: hr-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: irsa-sa # Assumed ServiceAccount with IRSA
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hr-app-secrets
  namespace: hr-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: hr-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: prod/hr-system/common
        property: DB_URL
    - secretKey: DB_USER
      remoteRef:
        key: prod/hr-system/common
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/hr-system/common
        property: DB_PASSWORD
    - secretKey: REDIS_HOST
      remoteRef:
        key: prod/hr-system/common
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: prod/hr-system/common
        property: REDIS_PORT
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: prod/hr-system/common
        property: JWT_SECRET_KEY
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: prod/hr-system/common
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: prod/hr-system/common
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: INTERNAL_TOKEN
      remoteRef:
        key: prod/hr-system/common
        property: INTERNAL_TOKEN
    - secretKey: GMAIL_USERNAME
      remoteRef:
        key: prod/hr-system/common
        property: GMAIL_USERNAME
    - secretKey: GMAIL_APP_PASSWORD
      remoteRef:
        key: prod/hr-system/common
        property: GMAIL_APP_PASSWORD
